### ISSUE TITLE
Help Tab on all Admin Pages

### ISSUE THREAD

**Issue by ThePoddi** [jschaefer-io/WP-Plugin-Boilerplate#1]
The Help Tab Content is showing on all Admin Pages. Should limited to the Plugin Pages?!

**Comment by jschaefer-io** [comment]
The help tab is meant to be a global help regarding shortcodes. I'll look into a separate help-tab to use on the plugin page only.

**Comment by jschaefer-io** [comment]
I added the requested feature with the latest commit: https://github.com/jschaefer-io/WP-Plugin-Boilerplate/commit/e1d8a63fec507a01bf4df6e95753f697d1a50687
Check the readme.md for the updated settings.
